import type { AppData, BodyZone } from "./types"
import { generateId, generateAccessToken } from "./storage"
import { DEFAULT_BODY_ZONES } from "./types"

export function getSeedData(): AppData {
  const now = new Date().toISOString()

  const bodyZones: BodyZone[] = DEFAULT_BODY_ZONES.map((zone) => ({
    ...zone,
    id: generateId(),
  }))

  // Хелпер для получения ID зоны по имени
  const getZoneId = (name: string) => bodyZones.find((z) => z.name === name)?.id || ""

  // 10 тестовых видео
  const videos = [
    {
      id: generateId(),
      title: "Упражнения для шейного отдела",
      description: "Комплекс упражнений для снятия напряжения в шее и улучшения мобильности",
      url: "https://example.com/videos/neck-exercises",
      thumbnailUrl: "/neck-stretching-exercises.jpg",
      duration: 480,
      bodyZones: [getZoneId("Шея"), getZoneId("Плечи")],
      tags: ["растяжка", "мобильность"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: "Растяжка поясницы",
      description: "Эффективные упражнения для расслабления поясничного отдела",
      url: "https://example.com/videos/lower-back-stretch",
      thumbnailUrl: "/lower-back-stretching.jpg",
      duration: 360,
      bodyZones: [getZoneId("Поясница")],
      tags: ["растяжка", "боль в спине"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: "Укрепление кора",
      description: "Упражнения для укрепления мышц центра тела",
      url: "https://example.com/videos/core-strength",
      thumbnailUrl: "/core-strengthening-exercise.jpg",
      duration: 600,
      bodyZones: [getZoneId("Живот"), getZoneId("Поясница")],
      tags: ["укрепление", "стабилизация"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: "Мобильность тазобедренного сустава",
      description: "Комплекс для улучшения подвижности тазобедренных суставов",
      url: "https://example.com/videos/hip-mobility",
      thumbnailUrl: "/hip-mobility-exercise.jpg",
      duration: 420,
      bodyZones: [getZoneId("Таз"), getZoneId("Бедра")],
      tags: ["мобильность", "суставы"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: "Упражнения для плечевого пояса",
      description: "Восстановление функции плечевого сустава",
      url: "https://example.com/videos/shoulder-rehab",
      thumbnailUrl: "/shoulder-exercise-therapy.jpg",
      duration: 540,
      bodyZones: [getZoneId("Плечи"), getZoneId("Лопатки")],
      tags: ["мобильность", "укрепление"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: "Дыхательная гимнастика",
      description: "Упражнения для улучшения дыхания и осанки",
      url: "https://example.com/videos/breathing-exercise",
      thumbnailUrl: "/breathing-exercise-relaxation.jpg",
      duration: 300,
      bodyZones: [getZoneId("Грудь"), getZoneId("Диафрагма")],
      tags: ["дыхание", "осанка"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: "Упражнения для стоп",
      description: "Укрепление и мобильность стоп и голеностопа",
      url: "https://example.com/videos/foot-exercises",
      thumbnailUrl: "/foot-strengthening-exercise.jpg",
      duration: 240,
      bodyZones: [getZoneId("Стопы"), getZoneId("Голени")],
      tags: ["мобильность", "баланс"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: "Растяжка задней поверхности тела",
      description: "Комплекс для снятия напряжения с задней миофасциальной цепи",
      url: "https://example.com/videos/posterior-chain",
      thumbnailUrl: "/posterior-chain-stretching.jpg",
      duration: 450,
      bodyZones: [getZoneId("Спина"), getZoneId("Бедра"), getZoneId("Голени")],
      tags: ["растяжка", "миофасциальный релиз"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: "Укрепление мышц спины",
      description: "Упражнения для профилактики болей в спине",
      url: "https://example.com/videos/back-strength",
      thumbnailUrl: "/back-strengthening-workout.jpg",
      duration: 660,
      bodyZones: [getZoneId("Спина"), getZoneId("Поясница")],
      tags: ["укрепление", "осанка"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: "Мобильность грудного отдела",
      description: "Упражнения для улучшения мобильности грудного отдела позвоночника",
      url: "https://example.com/videos/thoracic-mobility",
      thumbnailUrl: "/thoracic-spine-mobility.jpg",
      duration: 390,
      bodyZones: [getZoneId("Грудь"), getZoneId("Спина")],
      tags: ["мобильность", "осанка"],
      createdAt: now,
      updatedAt: now,
    },
  ]

  // 10 тестовых пациентов
  const patients = [
    {
      id: generateId(),
      name: "Иванов Иван Иванович",
      email: "ivanov@example.com",
      phone: "+7 (999) 123-45-67",
      notes: "Боли в поясничном отделе после длительного сидения",
      accessToken: generateAccessToken(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      name: "Петрова Мария Сергеевна",
      email: "petrova@example.com",
      phone: "+7 (999) 234-56-78",
      notes: "Ограничение подвижности в шейном отделе",
      accessToken: generateAccessToken(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      name: "Сидоров Алексей Дмитриевич",
      email: "sidorov@example.com",
      phone: "+7 (999) 345-67-89",
      notes: "Реабилитация после травмы плечевого сустава",
      accessToken: generateAccessToken(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      name: "Кузнецова Елена Павловна",
      email: "kuznetsova@example.com",
      phone: "+7 (999) 456-78-90",
      notes: "Профилактика болей в спине, офисная работа",
      accessToken: generateAccessToken(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      name: "Смирнов Дмитрий Александрович",
      email: "smirnov@example.com",
      phone: "+7 (999) 567-89-01",
      notes: "Нарушение осанки, кифоз грудного отдела",
      accessToken: generateAccessToken(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      name: "Волкова Ольга Николаевна",
      email: "volkova@example.com",
      phone: "+7 (999) 678-90-12",
      notes: "Головные боли напряжения",
      accessToken: generateAccessToken(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      name: "Морозов Сергей Викторович",
      email: "morozov@example.com",
      phone: "+7 (999) 789-01-23",
      notes: "Боли в тазобедренном суставе",
      accessToken: generateAccessToken(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      name: "Новикова Анна Игоревна",
      email: "novikova@example.com",
      phone: "+7 (999) 890-12-34",
      notes: "Послеродовое восстановление",
      accessToken: generateAccessToken(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      name: "Лебедев Михаил Андреевич",
      email: "lebedev@example.com",
      phone: "+7 (999) 901-23-45",
      notes: "Плоскостопие, боли в стопах",
      accessToken: generateAccessToken(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      name: "Соколова Татьяна Владимировна",
      email: "sokolova@example.com",
      phone: "+7 (999) 012-34-56",
      notes: "Хроническое напряжение в области шеи и плеч",
      accessToken: generateAccessToken(),
      createdAt: now,
      updatedAt: now,
    },
  ]

  // 5 шаблонов
  const templates = [
    {
      id: generateId(),
      name: "Комплекс при болях в пояснице",
      description: "Базовые упражнения для снятия напряжения и укрепления поясничного отдела",
      videoIds: [videos[1].id, videos[2].id, videos[8].id],
      tags: ["поясница", "боль"],
      createdAt: now,
    },
    {
      id: generateId(),
      name: "Программа для офисных работников",
      description: "Упражнения для профилактики болей при сидячей работе",
      videoIds: [videos[0].id, videos[5].id, videos[9].id, videos[2].id],
      tags: ["офис", "профилактика"],
      createdAt: now,
    },
    {
      id: generateId(),
      name: "Восстановление после травмы",
      description: "Комплекс для постепенного восстановления после травм",
      videoIds: [videos[4].id, videos[7].id],
      tags: ["реабилитация", "травма"],
      createdAt: now,
    },
    {
      id: generateId(),
      name: "Улучшение осанки",
      description: "Упражнения для коррекции осанки и укрепления мышц спины",
      videoIds: [videos[5].id, videos[8].id, videos[9].id],
      tags: ["осанка", "спина"],
      createdAt: now,
    },
    {
      id: generateId(),
      name: "Базовая мобильность",
      description: "Общий комплекс для улучшения подвижности всего тела",
      videoIds: [videos[0].id, videos[3].id, videos[6].id, videos[9].id],
      tags: ["мобильность", "общее"],
      createdAt: now,
    },
  ]

  // Тестовые назначения
  const assignments = [
    {
      id: generateId(),
      patientId: patients[0].id,
      title: "Комплекс для поясницы",
      description: "Выполнять 2 раза в день, утром и вечером",
      videoIds: [videos[1].id, videos[2].id],
      videoOrder: [videos[1].id, videos[2].id],
      expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      isActive: true,
      createdAt: now,
    },
    {
      id: generateId(),
      patientId: patients[1].id,
      title: "Упражнения для шеи",
      description: "Начинать медленно, без резких движений",
      videoIds: [videos[0].id, videos[5].id],
      videoOrder: [videos[0].id, videos[5].id],
      expiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      isActive: true,
      createdAt: now,
    },
  ]

  return {
    videos,
    patients,
    assignments,
    videoViews: [],
    templates,
    bodyZones, // добавлены зоны тела
  }
}
